export type VisualScene = {
  id: string;
  title: string;
  image: any;      // require() 결과
  tiles20: string[]; // 화면에 보여줄 타일 20개(괄호 금지)
};

function clean(list: string[]) {
  // 괄호 제거(요구사항) + trim + 빈값 제거
  return list
    .map((s) => s.replace(/[()]/g, "").trim())
    .filter(Boolean)
    .slice(0, 20);
}

export const VISUAL_SCENES: VisualScene[] = [
  {
    id: "city",
    title: "도심",
    image: require("../../../assets/grounding/city.jpeg"),
    tiles20: clean([
      "빨간 전화부스",
      "택시",
      "버스정류장",
      "거리 시계",
      "가로등",
      "신호등",
      "횡단보도",
      "쓰레기통",
      "자전거",
      "우체통",
      "플랜터",
      "가로수",
      "난간",
      "계단",
      "표지판",
      "맨홀 뚜껑",
      "배수구",
      "카페 테이블",
      "카페 의자",
      "유틸리티 박스",
    ]),
  },
  {
    id: "desk",
    title: "책상",
    image: require("../../../assets/grounding/desk.jpeg"),
    tiles20: clean([
      "노트북",
      "모니터",
      "키보드",
      "마우스",
      "스탠드 조명",
      "노트",
      "포스트잇",
      "가위",
      "자",
      "계산기",
      "스마트폰",
      "손목시계",
      "물병",
      "머그컵",
      "헤드폰",
      "티슈박스",
      "탁상 캘린더",
      "액자",
      "화분",
      "케이블",
    ]),
  },
  {
    id: "park",
    title: "공원",
    image: require("../../../assets/grounding/park.jpeg"),
    tiles20: clean([
      "미끄럼틀",
      "그네",
      "시소",
      "클라이밍 구조물",
      "벤치",
      "피크닉 테이블",
      "분수",
      "안내 표지판",
      "지도판",
      "게시판",
      "재활용통",
      "쓰레기통",
      "자전거",
      "자전거 거치대",
      "유모차",
      "화분",
      "잔디",
      "울타리",
      "축구공",
      "연",
    ]),
  },
  {
    id: "kitchen",
    title: "부엌",
    image: require("../../../assets/grounding/kitchen.png"),
    tiles20: clean([
      "가스레인지",
      "프라이팬",
      "냄비",
      "주전자",
      "토스터",
      "커피메이커",
      "블렌더",
      "도마",
      "칼",
      "양파",
      "토마토",
      "싱크대",
      "수도꼭지",
      "식기건조대",
      "접시",
      "컵",
      "수세미",
      "주방세제",
      "키친타월",
      "향신료병",
    ]),
  },
  {
    id: "classroom",
    title: "어린이집",
    image: require("../../../assets/grounding/classroom.png"),
    tiles20: clean([
      "수납장",
      "수납박스",
      "원형 러그",
      "테이블",
      "의자",
      "블록",
      "퍼즐",
      "주판",
      "탬버린",
      "실로폰",
      "크레용",
      "종이",
      "글루스틱",
      "바구니",
      "장난감 자동차",
      "인형집",
      "화이트보드",
      "벽시계",
      "가방",
      "매트",
    ]),
  },
];
